GOOSE_MODEL: gemini-2.0-flash-exp
extensions:
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
GOOSE_PROVIDER: google
